name: Deploy to Hetzner via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Project
      run: |
        npm install
        npm run build

    - name: Deploy via SFTP (with cleanup)
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        protocol: sftp
        local-dir: "out/"
        server-dir: ${{ secrets.FTP_PATH }}
        dangerous-clean-slate: true  # Enables deletion of old files
        exclude: |
          **/*.map
